%%------------write Matrix A results to excel
%print matrix A
T31 = table(A(1,:)',A(2,:)',A(3,:)',A(4,:)',A(5,:)',A(6,:)',...
    A(7,:)',A(8,:)',A(9,:)',A(10,:)',...
    'VariableNames',{'GW','Acidification','Eutrophication','Land','FWC','Energy','Whole_fish','Mangrove_land','freshwater_land','mass'},...
    'RowNames',{GH{1},GH{2},GH{3},GH{4},GH{5},GH{6},...
        GH{7},GH{8},GH{9},GH{10},GH{11},...
        GH{12}});
writetable(T31,dr,'FileType','spreadsheet','WriteRowNames',true,'Sheet','Matrix A')

%%
%print shadow prices
Labels={'All','zinc','iron','calcium','vitamin A','iodine'};
if strcmp(R,'MC_Random');draw_SensitivityAnalysis_indo(C,xmt,R,Labels);
T13 = table(Impactful_constraint(:,1),Impactful_constraint(:,2),Impactful_constraint(:,3),...
        Impactful_constraint(:,4),Impactful_constraint(:,5),Impactful_constraint(:,6),...
         'VariableNames',{'all','zinc','iron','calcium','vitamin_A','iodine'},...
    'RowNames',{'GW','Acidification','Eutrophication','Land','FWC','Energy','whole fish','Mangrove land','freshwater_land','mass'});
writetable(T13,dr,'FileType','spreadsheet','WriteRowNames',true,'Sheet','enviro. constraints');

end
if strcmp(R,'normal');T12 = table(sensitivity(:,1),sensitivity(:,2),sensitivity(:,3),...
        sensitivity(:,4),sensitivity(:,5),sensitivity(:,6),...
         'VariableNames',{'all','zinc','iron','calcium','vitamin_A','iodine'},...
    'RowNames',{'GW','Acidification','Eutrophication','Land','FWC','Energy','Whole fish','Mangrove land','freshwater_land','mass'});
writetable(T12,dr,'FileType','spreadsheet','WriteRowNames',true,'Sheet','Sensitivity Analysis');


end